### ISSUE TITLE
Exception on building a Project with ManagedAction

### ISSUE THREAD

**Issue by jfquarto** [oleg-shilo/wixsharp#1066]
Using:

- VS2019
- WixSharp 1.10.0

Added a ManagedAction:

`        var project =
            new Project("ProjectX",
                new LaunchCondition("VersionNT >= 601", "Windows 7 or higher required"),
                new ManagedAction(CustomActions.MyAction, Return.check, When.Before, Step.LaunchConditions, Condition.NOT_Installed),
`

The (simplified) custom action:

```
public class CustomActions
{
    [CustomAction]
    public static ActionResult MyAction(Session session)
    {
        return ActionResult.Success;
    }
}
```

Building the VS solution generates this error:

**Unhandled Exception: System.Exception: WiX SDK binaries cannot be found. Please set WixSharp.Compiler.WixSdkLocation to valid path to the Wix SDK binaries.**
1>     at WixSharp.WixBinLocator.FindWixSdkLocation(String wixLocation)
1>     at WixSharp.Compiler.get_WixSdkLocation()
1>     at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
1>     at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
1>     at WixSharp.Compiler.GenerateWixProj(Project project)
1>     at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
1>     at WixSharp.Compiler.Build(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.BuildMsi(Project project, String path)
1>     at WixSharp.Project.BuildMsi(String path)
1>     at Script.Main(String[] args)

When I remove the ManagedAction from the Project instancing, the VS solution builds just fine.

**Comment by oleg-shilo** [comment]
It looks like you do not have WiX installed or it is installed in an unknown location.
This article can help: https://github.com/oleg-shilo/wixsharp/wiki/Building-MSI-%E2%80%93-Step-by-step-tutorial.

**Comment by oleg-shilo** [comment]
I am not sure setting the location this way is safe. Is it the "bin" folder containing WiX compilers?
![image](https://user-images.githubusercontent.com/16729806/136211530-1c2ecd49-fa4f-4da4-afe3-018f55bc85ba.png)

The safest way to bring the binaries is to install WiX in the well-known location (e.g. Program Files) but not in the `bin\Debug\Tools\Wix\311`.

Alternatively, you may import `Install-Package WixSharp.wix.bin` as it is described in the article I shared

**Comment by jfquarto** [comment]
The WixLocation setting was done as part of an attempt to build the installer in Azure CI (pipeline), found this in an article about this on the web.
Now I see the problem, the SDK map was missing.

**Comment by jfquarto** [comment]
Solved
