### ISSUE TITLE
Error: Dependent assembly not supplied: System.Drawing, Version=2.0.0.0

### ISSUE THREAD

**Issue by jiakuan** [oleg-shilo/wixsharp#112]
I have a script to build MSI installer using WixSharp 1.4.7.0, which worked perfectly on Windows 7 32 bit, but when I tried the same script on Windows 10 64bit, I got the following errors:
```
----------------------------------------------------------
Building MSI file...
----------------------------------------------------------
Searching for custom action entry points in msi_build.cs.compiled
    Loaded dependent assembly: C:\apps\WixSharp.1.4.7.0\Wix_bin\sdk\Microsoft.Deployment.WindowsInstaller.dll
    MyAction=msi_build.cs!CustomActions.MyAction
Searching for an embedded UI class in msi_build.cs.compiled
Modifying SfxCA.dll stub
Copying file version info from C:\work\my-app\msi_build.cs.compiled to C:\work\my-app\%this%.CA.dll
Packaging files
    msi_build.cs.compiled
    CustomAction.config
    WixSharp.dll
    Microsoft.Deployment.WindowsInstaller.dll
MakeSfxCA finished: C:\work\my-app\%this%.CA.dll
Searching for custom action entry points in WixSharp.dll
    Loaded dependent assembly: C:\apps\WixSharp.1.4.7.0\Wix_bin\sdk\Microsoft.Deployment.WindowsInstaller.dll
    Error: Dependent assembly not supplied: System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d
50a3a
Error: System.IO.FileLoadException: Cannot resolve dependency to assembly 'System.Drawing, Version=2.0.0.0, Culture=neut
ral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent a
ssemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.FindEntryPoints(String module)
   at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Build(String output, String sfxdll, IList`1 inputs, TextWriter log)
   at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Main(String[] args)
Error: Specified file could not be executed.

System.ApplicationException: Cannot package ManagedCA assembly(C:\apps\WixSharp.1.4.7.0\WixSharp.dll)
   at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String co
nfigFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
   at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
   at WixSharp.Compiler.GenerateWixProj(Project project)
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
   at WixSharp.Compiler.Build(Project project, OutputType type)
   at Script.Main(String[] args)
A duplicate file name exists, or the file
cannot be found.
PS C:\work\my-app>
```

I've tried to research the root cause from Google a few hours, still haven't got a clue. Is WixSharp.1.4.7.0 expected to work correctly on Windows 10 64bit? Thanks.

**Comment by oleg-shilo** [comment]
Hi Jake,

It was quick. :) 

Since WixSharp.1.4.7.0 was released just 2 hours ago I would like to ensure the health of this release. I am running it on Win10 x64 without any problems. Can you please test if you can build the same MSI from VS with the latest NuGet package (WixSharp.1.4.7.0)?

We will proceed from there.

**Comment by jiakuan** [comment]
@oleg-shilo Thanks for your quick response. It was because of my system environment. After I enabled .NET 3.5 and installed WiX Toolset separately, it worked like a charm. Thank you.

**Comment by oleg-shilo** [comment]
OK, great. 
Can you please elaborate about "I enabled .NET 3.5"? Did you mean "installed .NET 3.5"?

**Comment by jiakuan** [comment]
It's actually enabled from "Turn Windows features on or off" dialog from users' perspective, although it will download some files as needed. I followed the steps mentioned on [this page](https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/how-to-instal-net-framework-35-on-windows-10/450b3ba6-4d19-45ae-840e-78519f36d7a4) to enable .NET 3.5.

**Comment by oleg-shilo** [comment]
thank you
