### ISSUE TITLE
System.MissingMethodException: No parameterless constructor defined for this object.

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1353]
Hi,
I'm using Wixsharp version 1.22
I create a project:
`new ManagedProject("ProjectName", fileTree)`
and I use AfterInstall action:
` installer.AfterInstall += OnAfterInstall;`
```
  private void OnAfterInstall(SetupEventArgs e)
{
...
}
```
trying to install, the installation failed and i get the following error:
```
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
WixSharp aborted the session because of the error:
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   at WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)
CustomAction WixSharp_AfterInstall_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:34:19: InstallFinalize. Return value 3.
```

**Comment by oleg-shilo** [comment]
Quite possibly your target system does not have the required .NET installed.

If it's the case then you need to use a bundle. either NSIS or WiX one:

![Uploading image.png…]()
