### ISSUE TITLE
XML exception when run CustomMSIDialog sample

### ISSUE THREAD

**Issue by exaw** [oleg-shilo/wixsharp#1358]
I can't to build custom MSI dialog from WixForm, e.g., CustomMSIDialog sample throws when building:

Packaging files
    setup.exe
    CustomAction.config
    setup.pdb
    WixSharp.dll
    Microsoft.Deployment.WindowsInstaller.dll
    WixSharp.Lab.dll
MakeSfxCA finished: D:\cygwin64\home\code\cadexsdk\Wix# Samples\Custom_UI\CustomMSIDialog\bin\Debug\%this%.CA.dll

Unhandled Exception: System.ArgumentException: '' is an invalid expanded name.
   at System.Xml.Linq.XName.Get(String expandedName)
   at WixSharp.Extensions.AddAttributes(XElement obj, Dictionary`2 attributes)
   at WixSharp.Controls.Control.ToXElement()
   at WixSharp.Controls.Dialog.ToXElement()
   at WixSharp.Controls.CustomUI.ToXElement()
   at WixSharp.Compiler.IndjectCustomUI(CustomUI customUI, XDocument doc)
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
   at WixSharp.Compiler.Build(Project project, OutputType type)
   at Script.Main() in D:\cygwin64\home\code\cadexsdk\Wix# Samples\Custom_UI\CustomMSIDialog\setup.cs:line 49

How it can be repaired?

**Comment by oleg-shilo** [comment]
Can you confirm which version of WixSharp you are trying to build with?

**Comment by exaw** [comment]
> Can you confirm which version of WixSharp you are trying to build with?

WixSharp 1.22.1
WixSharp.bin 1.22.1
WixSharp.Lab 1.22.1
WixSharp.wix.bin 3.14.0

**Comment by oleg-shilo** [comment]
Yes, it is a defect in the WiX3 targeting version of WixSharp. I just have updated the sample with the fix.

BTW the later WixSharp versions, which target WiX4, have dropped support for CustomMSI dialogs developed with WiX markup. The reason for this is that this feature has very little engagement with the users and the technology has been replaced with by far superior technique of building custom dialogs with WinFirm and WPF.

But your version still supports both techniques.

I suggest you consider switching to WinForm-based custom UI. You can create your project from the "WixSharp - Custom UI" VS project template. (you will need to install WixSharp Visual Studio extension).

If you really keen to use that sample you need to update you sample from repo `wix-v3-master`. Or you just remove `\r\n` from this code manually:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/2e79ab35-e16b-4353-b416-c772e2628d10)

**Comment by exaw** [comment]
Oleg, thanks for the quick reply!
Now I study different ways to create installer, both MSI native dialogs and WinForms.
