### ISSUE TITLE
Hidden NullReferenceException in Extensions.GetEmbeddedData

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#1431]
We attached an event handler FirstChanceException to early find and register hidden exceptions in our code. In combination with WixSharp 1.2.0 we consistently see the following:

```
2024-01-19 07:16:11: itgenmsi501: First chance exception handling of type 'NullReferenceException':
2024-01-19 07:16:11: itgenmsi502: Object reference not set to an instance of an object.
2024-01-19 07:16:11: itgenmsi504: Stack trace:
2024-01-19 07:16:11: itgenmsi505:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at SIDY.PQ.A()
   at Invantive.Deploy.Error.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e)
   at WixSharp.Extensions.GetEmbeddedData(Session session, String binary)
   at WixSharp.MsiSessionAdapter.GetResourceData(String name)
   at WixSharp.UIShell.<>c__DisplayClass45_0.<ShowModal>b__1(Object s, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.ShowWindow(HandleRef hWnd, Int32 nCmdShow)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at WixSharp.UIShell.ShowModal(InstallerRuntime runtime, IManagedUI ui)
   at WixSharp.ManagedUI.<>c__DisplayClass31_1.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The upper method `Invantive.Deploy.Error.CurrentDomain_FirstChanceException` is the event handler. The method `SIDY.PQ.A` is an obscured (CryptoObfuscator) private method within the event handler.

The null reference occurs early during the execution of the installer and is eaten away somewhere in the call stack, since there are no visible damage done to the process itself.

However, it is not very elegant and can be a cause of an actual issue.

Maybe the code can be made more robust (or improved using `<Nullable>annotations</Nullable>` and error on CS86xx warnings).

**Comment by oleg-shilo** [comment]
Hi Guido,

By default, I prefer not to catch the exceptions for only rethrowing them with a "nicer" message. And I think it is the only option here as the exception is coming from the winform OnLoad event handler of the form that is somehow is not initialized as expected. This is my assumption though.

But I do not want to dismiss your proposal, so can share what is that dialog. 
- Is it custom or WixSharp stock dialog?
- Is it still displayed after the exception? seems like it is.
- Does it have the intended background image? (`GetResourceData` is trying to extract the image from the msi)

**Comment by oleg-shilo** [comment]
I might know the answer. even though I haven't yet your answers yet.

Most likely you are using WiX3 build and using "custom WPF UI" VS project template.
If this is the case then indeed the symptoms you are observing are caused by the incorrect dialog initialization. Thus having the exception thrown is important for troubleshooting problems like this.

The `incorrect dialog initialization` is caused by the typo in the template - an unfortunate leakage of WiX4 code in WiX3 codebase.
This is a heavy price for maintaining two codebases fro the same product (WiX3 and WiX4) 😞 

I will be releasing the patch for the templates. But until then you can address the problem by changing the initialization code like this:

```C#
    internal class *DialogModel : Caliburn.Micro.Screen
    {
        public ManagedForm Host;
        . . .
        // replace
        // public BitmapImage Banner => session?.GetResourceBitmap("WixUI_SharpBmp_Dialog").ToImageSource();

        // with
        public BitmapImage Banner => session?.GetResourceBitmap("WixUI_Bmp_Dialog").ToImageSource();
        
```

----

Unless, of course you are dealing with a completely different problem.

**Comment by monty241** [comment]
Thanks for the suggestion! We solely use Winforms (no WPF), and the bitmaps seem to work fine (WixUI_Bmp_Dialog and WixUI_Bmp_Banner). Solely the first chance exception handler is triggered by a NRE. I am awaiting a new release and will update accordingly.

**Comment by oleg-shilo** [comment]
OK, then I will proceed with the release but I do not expect it to make any difference regarding your problem.

I did update the code:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/44339af3-1c08-4fd0-8374-fdc50c24f7a7)

But it would prevent a pair of throw-n-catch only if the bitmap is not found. But you are saying it is.... so it's not your case.

**Comment by monty241** [comment]
Thanks nonetheless! I am a very happy user of WixSharp. Localizations are also working great now!

**Comment by oleg-shilo** [comment]
Glad it all worked out for you :)
