### ISSUE TITLE
Trying to configure a file in the install folder

### ISSUE THREAD

**Issue by isaachaz** [oleg-shilo/wixsharp#1448]
I have created a custom action that tries to edit a config files in the install folder.
The install folder is located at: C:\Program Files\MyCompany\MySoftware\MyAgent.dll.config'

The code of the action is pretty simple as follows:
`    
public static ActionResult ConfigureAQCForFIQC(Session session)
    {
        var logger = new Logger(session);
        string filePath = "c:\\temp\\iqc.log";
        try
        {

            string productToInstall = session["PRODUCT_TYPE_TO_INSTALL"];

            if (productToInstall == "AQC")
            {
                string configFilePath = System.IO.Path.Combine(session.Property("INSTALLDIR"), "MyAgent.dll.config");

                XmlDocument doc = new XmlDocument();
                doc.Load(configFilePath);
        
                logger.Log($"Successfully loaded: {configFilePath}");
                logToFilePath(filePath, $"Successfully loaded: {configFilePath}");
        
                XmlNode appSettingsNode = doc.SelectSingleNode("/configuration/appSettings");
                if (appSettingsNode != null)
                {
                    XmlNode aqcRunnerModeNode = appSettingsNode.SelectSingleNode("add[@key='AQCRunnerMode']");
                    if (aqcRunnerModeNode != null)
                    {
                        aqcRunnerModeNode.Attributes["value"].Value = "true";
                    }
                }
        
                doc.Save(configFilePath);
            }
        }
        catch (Exception e)
        {
            logger.Log("Failed to configure the TQC Runner Mode for Intel Quality Center");
            logToFilePath(filePath, "Failed to configure the TQC Runner Mode for Intel Quality Center");
            logger.Log($"ConfigureTQCForIQC throw exception: {e}");
            logToFilePath(filePath, $"ConfigureTQCForIQC throw exception: {e}");
            return ActionResult.Failure;
        }
        
        return ActionResult.Success;
    }
`

I go an unauthorized exception when running that as follows:
`
ConfigureAQCForFQC throw exception: System.UnauthorizedAccessException: Access to the path 'C:\Program Files\MyCompany\MySoftware\MyAgent.dll.config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlDocument.Save(String filename)
   at CustomActions.ConfigureTQCForIQC(Session session) in C:\code\applications.validation.thunderbolt.tbt-sw-tqc\Installer\Installer\CustomActions.cs:line 206
`

I create the CustomAction as follows:

`
                  new ElevatedManagedAction(CustomActions.ConfigureTQCForIQC, Return.check, When.After,
                          Step.InstallExecute, Condition.NOT_Installed)
                      {Execute = Execute.immediate, Impersonate = false}

`

Any clue what could be the reason or the method to do such?

Thx in advance

**Comment by oleg-shilo** [comment]
In order to modify any file in ProgramFiles you need to be elevated. You are using raw CA that is not elevated.
I would recommend that you switch to the managed project and use project events (CA wrapped as a .NET event):

```C#
project.AfterIsntall += e =>
{
    if (e.IsInstalling)
    {
        string configFilePath = e.InstallDir.PathCombine("MyAgent.dll.config");
        . . .
    }
};
```

And `project.AfterIsntall` is already elevated.

**Comment by oleg-shilo** [comment]
> Switching to a ManagedProject is not really an option right now as it would be a big change

Actually, it is not. `ManagedProject` is a `Project` but with events. That's it. Your runtime dependencies are not going to change, your setup definition is not going to change. So I am kinda curious, why do you think it is a big change?

**Comment by isaachaz** [comment]
Is it possible to fail the install from AfterInstall event in case it does not succeed to configure the file?

**Comment by oleg-shilo** [comment]
Yes, it is possible. 

MSI/WiX implemented elevated actions as deferred actions, meaning you cannot access the setup session. The session is already closed. That's why it's called **After**Install.

You can preserve some session data in your early events for use in the future `AfterInstall`. You will need to mark some of your session properties as one to be used in deferred actions.

```C#
project.DefaultDeferredProperties += ",ADDLOCAL"; 
```
The SetupEvents sample I suggested to you shows this technique as well as the simplified pure WixSharp alternative `"persisted_data"`.

. . .

Saying that, I encourage you to review your deployment approach. You7 might be following the deployment anti-pattern of coupling deployment and configuration. Ideally you want to separate fully your deployment and configuration. Thus the deployment is implemented as msi session (your msi file) and the configuration as an application workflow (e.g. your app or a config utility). Even though the config workflow is executed immediately after the installation.
