### ISSUE TITLE
BuildMsi is throwing System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by jamesdraughn** [oleg-shilo/wixsharp#1498]
My project builds fine through visual studio, however on our build server I am getting the following exception:

2024-04-10T19:25:21.4953554Z PostBuild:
2024-04-10T19:25:21.4953620Z   "bin\Release\net472\WixSharp.AmsSyncInstaller.exe"
2024-04-10T19:25:22.0876802Z   
2024-04-10T19:25:22.1199985Z   Unhandled Exception: System.IO.DirectoryNotFoundException: D:\Agent\_work\141\s\asdf\WixInstallerUpgrade\AMS.Sync.Manager.UI\bin\Release\net6.0-windows
2024-04-10T19:25:22.1200310Z      at WixSharp.Files.GetAllItems(String baseDirectory, Dir parentWixDir)
2024-04-10T19:25:22.1200389Z      at WixSharp.Project.ResolveWildCards(Boolean pruneEmptyDirectories)
2024-04-10T19:25:22.1200490Z      at **WixSharp.Compiler.ProcessDirectories**(Project wProject, Dictionary``2 featureComponents, List``1 defaultFeatureComponents, List``1 autoGeneratedComponents, XElement dirs)
2024-04-10T19:25:22.1200599Z      at WixSharp.Compiler.GenerateWixProj(Project project)
2024-04-10T19:25:22.1200697Z      at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
2024-04-10T19:25:22.1200774Z      at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
2024-04-10T19:25:22.1200847Z      at WixSharp.Compiler.Build(Project project, String path, OutputType type)
2024-04-10T19:25:22.1201284Z      at WixSharp.Compiler.Build(Project project, OutputType type)
2024-04-10T19:25:22.1201353Z      at WixSharp.Project.BuildMsi(String path)
2024-04-10T19:25:22.1201450Z      at WixSharp.AmsSyncInstaller.Program.BuildAmsSyncManagerInstaller() in D:\Agent\_work\141\s\asdf\WixInstallerUpgrade\WixSharp.AmsSyncInstaller\Program.cs:line 478
2024-04-10T19:25:22.1201587Z      at WixSharp.AmsSyncInstaller.Program.Main(String[] args) in D:\Agent\_work\141\s\asdf\WixInstallerUpgrade\WixSharp.AmsSyncInstaller\Program.cs:line 169
2024-04-10T19:25:22.8630196Z ##[error]asdf\WixInstallerUpgrade\WixSharp.AmsSyncInstaller\WixSharp.AmsSyncInstaller.csproj(111,3): Error MSB3073: The command ""bin\Release\net472\WixSharp.AmsSyncInstaller.exe"" exited with code -532462766.

I don't know if this has anything to do with the problem, but I notice that the **WixSharp.Compiler.ProcessDirectories** method is referencing "%ProgramFiles%", and our build server runs from the **D:\\**, and does not allow access to the C:\ or any of its directories.

![Snag_14ebcdf](https://github.com/oleg-shilo/wixsharp/assets/84732883/3493ef29-7757-4a76-bf77-92cdb8633e09)

**Comment by oleg-shilo** [comment]
No, `%ProgramFiles%` refers to the destination folder - "Program Files" on your target system. 
That's is not the problem.

The log is saying that your `D:\Agent_work\...\AMS.Sync.Manager.UI\bin\Release\net6.0-windows` is not found. That is strange as `ResolveWildCards` discovered that this directory exists, but when it tries to look inside of it throws the "not-found" exception.

Is it possible that the dir in question has special permissions or there is come competing activity (e.g. cleaning) that deletes the folder before we process it?

**Comment by jamesdraughn** [comment]
Looks like it was a competing activity. Thanks for your time.
