### ISSUE TITLE
Upgrade Project with BA Installer from .NET 4.8 to NET 8.0 or better

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#1518]
Morning, i upgrade my mainproject with BA Installer from  .NET 4.8 to NET 8.0.  I use MS Upgrade Assistent. Now i cant even start it. Rebuild and publishing is successful, but if i start i got error in Windows Eventlog 
Application: WpfSetup.exe
CoreCLR Version: 8.0.424.16909
.NET Version: 8.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'WpfSetup, Version=1.5.2.2024, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'WpfSetup, Version=1.5.2.2024, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at WpfSetup.SplashScreen.InitializeComponent()
   at WpfSetup.SplashScreen..ctor()
   at WpfSetup.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at WpfSetup.App.Main()

I also install new Mba.Core from WixToolset and Wixsharp. Nothing helps. Is library Wixsharp.MSI.dll not compatible with NET 8.0 ? 8.0.4 is installed on Testmachine. Any Idea or how to i properly upgrade project from NET 4.8 to NET 8.0 ?

**Comment by Torchok19081986** [comment]
after research and tries. I could make it work. Delete app.manifest, app.config and most important step add into project description. Also add 

```xml
 <TargetFrameworks>net4.8;net8.0-windows</TargetFrameworks>
```
instead of  <TargetFramework>net8.0-windows</TargetFramework>

```xml

 <LangVersion>latest</LangVersion>

```
Somehow after upgrade, project thinking it at .NET Version of C# 7.3, and not 8.0. Dont know why. 
now publishing into folder destionation can be run. 🤔🤔🤔.

**Comment by oleg-shilo** [comment]
WiX (and consequently WixSharp) only supports .NET Framework and .NET 8.0 is a .NET Core family.

So, to put it simple, it's not expected to work even though technically it's possible to use to emit raw MSIs with .NETCore any other scenarios like managed CA will be broken.


Saying that, WixSharp has released a few months ago a .NET Core  package (you will find it in VS templates). It's an aggressive solution as WiX cannot work with Core assemblies so all CA assemblies are compiled in native ahead of compilation libraries.

It has some limitations and it only covers msi building but not the bootstrapper.

**Comment by Torchok19081986** [comment]
ok, all i can do now is, installer in .NET Framework and Programm into NET 8.0. Not my first choice, but if it at moment not possible use whole NET 8.0 for both, i do it so. Thanks, again.

**Comment by oleg-shilo** [comment]
Certainly. You can easily author your msi with .NET Core.

Just use the appropriate template

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/bc8fb78f-b4e6-4bf1-bc07-5187117dba06)

**Comment by oleg-shilo** [comment]
Certainly. You can easily author your msi with .NET Core.

Just use the appropriate template

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/bc8fb78f-b4e6-4bf1-bc07-5187117dba06)

**Comment by oleg-shilo** [comment]
I have also aggregated all .NET Core information here:
https://github.com/oleg-shilo/wixsharp/wiki/.NET-Core-support
