### ISSUE TITLE
Object reference not set to an instance of an object. at WixSharp.Extensions.AddWixFragment(XElement placementElement, XElement[] content)

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#164]
When you add this one:

    product.WixMsiFragments.Add(new Tuple<string, WixSharp.IXmlAware>("Wix123/Product567", new UtilFileSearch { Path = @"[WindowsFolder]Microsoft.NET\Framework64\v4.0.30319\CONFIG\machine.config", Result = SearchResult.exists, Variable = "NET40_64_BITS_MACHINE_CONFIG" }));

you get an null reference exception:

```
   at WixSharp.Extensions.AddWixFragment(XElement placementElement, XElement[] content)
   at WixSharp.WixProject.InvokeWixSourceGenerated(XDocument doc)
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildMsi(Project project, String path)
```

Probably the Wix123/Product567 causes it.

**Comment by oleg-shilo** [comment]
This does not look like Wix# code. I am guessing it is your custom Wix# routine/extension. If it is the case then only you can possible know what it does :)

Indeed most likely your path `Wix123/Product567` returns a null XElement that then is used for `placementElement`.

**Comment by monty241** [comment]
Sorry, was ultimately a call to AddWixFragment in Wix#. On build time it then failed. But the fragments code has been removed now, so can not find and closing.
