### ISSUE TITLE
FileLoadException due to "Strong name validation failed." when loading dialogs

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#1693]
I am puzzling how to solve a 1603 installation error created by an MSI created using WixSharp 1.26.0. It is caused by a `FileLoadException`.

The 1603 seems to have started appearing after we switched to EV Code Signing, but many parallel changes were made across the build process to allow use of EV Code Signing with a hardware token on a cloud Windows build device.

## Visible problem

Running with `msiexec /i MSI_FILE /L*vx log.txt` reveals that it installs the following files in a temporary folder (according to lines with `FDeleteFolder` in the msi installation log):

...\MSI32458\Acme.Deploy.dll
...\MSI32458\Acme.Deploy.Runtime.dll
...\MSI32458\Acme.Deploy.UI.dll
...\MSI32458\BootstrapperCore.dll
...\MSI32458\EmbeddedUI.config
...\MSI32458\Microsoft.Deployment.WindowsInstaller.dll
...\MSI32458\Newtonsoft.Json.dll
...\MSI32458\PhoneNumbers.dll
...\MSI32458\WixSharp.dll
...\MSI32458\WixSharp.UI.CA.dll
...\MSI32458\WixSharp.UI.dll

And fails with `System.IO.FileLoadException` on `Cannot attach ManagedUI: `: 

```
Can not load file or assembly Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679 or one of the dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679 ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

and call stack:
```
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at WixSharp.ManagedProject.GetDialog(String info)
   at WixSharp.ManagedProject.<>c.<ReadDialogs>b__41_2(String x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList(IEnumerable`1 source)
   at WixSharp.ManagedProject.ReadDialogs(String data)
   at WixSharp.ManagedUI.ReadDialogs(Session session)
   at WixSharp.ManagedUI.Initialize(Session session, String resourcePath, InstallUIOptions& uiLevel)
   at Microsoft.Deployment.WindowsInstaller.EmbeddedUIProxy.Initialize(Int32 sessionHandle, String uiClass, Int32 internalUILevel)
```

## WixSharp Code

The `GetDialog` method in the callstack has the following code:

```
internal static Type GetDialog(string info)
{
    string[] parts = info.Split('|');

    var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(x => x.GetName().Name.StartsWith(parts[0]))
                   ??
                   System.Reflection.Assembly.Load(parts[0]);

    var dialogType = assembly.GetType(parts[1]);
    if (dialogType == null)
        throw new Exception($"Cannot instantiate '{parts[1]}'. " +
                            $"Make sure you added this type assembly to your setup with 'project.{nameof(DefaultRefAssemblies)}'");

    return dialogType;
}
```

so it first splits the text on '|', and then searches the available assemblies for the name that starts with the text left of the first '|'. When found, a call to `Reflection.Assembly.Load` loads that one.

The second element after the first '|' and before end/next '|' is the type of the dialog.

Given the call stack, `GetDialog` gets called from `ReadDialogs` in `ManagedProject.cs`, which separates multiple entries separated by line feeds `&#xA` to return all needed dialog types.

## WXS definition

The *.wxs file used to build the file contains a few references to `Acme.Deploy.UI`:

```
<Property Id="WixSharp_InstallDialogs" Value="Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.WelcomeDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.InstallDirDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.EmailAddressDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.PersonalDataDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.ProgressDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.ExitDialog" />
<Property Id="WixSharp_ModifyDialogs" Value="Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.MaintenanceTypeDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.ProgressDialog&#xA;Acme.Deploy.UI, Version=24.0.507.0, Culture=neutral, PublicKeyToken=5dbbce36fbd59679|Acme.Deploy.UI.ExitDialog" />
```

Indeed these match the format expected by `ReadDialogs` and all are based on the same assembly.

## Signed? Yes.

The DLLs found in the input folder for WixSharp are all properly signed (with the expected public key token). It was validated that these DLLs are included by full path in `wixManagedProject.DefaultRefAssemblies`.

It seem that the `DefaultRefAssemblies` are resolved with their dependencies in a temporary domain and then bundled into a row in the table `MsiEmbeddedUI` for a named `WixSharp.UI.CA.dll`.

## Question

The analysis has reached so far, but without solution.

What is an alternative approach to discover the reason of the `FileLoadException` and solve it?

**Comment by monty241** [comment]
A PR was added to make solution of such problem easier for the future. 

Any help is still very much appreciated, since I am stuck it seems due to insufficient knowledge.

**Comment by oleg-shilo** [comment]
A very exhaustive analysis in the OP.
An thank you fore the comprehensive PR. The change will be available in the very next release.

**Comment by monty241** [comment]
Ultimately, the problem was found to be indeed that parts of the build chain used only code signing and no strong name signing, leading to the error indicated. The error indicated by WixSharp was correct.
