### ISSUE TITLE
Error while using MSIRuntime.Session.Log in OnExecuteComplete

### ISSUE THREAD

**Issue by bhagatus** [oleg-shilo/wixsharp#1705]
Hi Oleg,

I have observed error while using MSIRuntime.Session.Log at event OnExecuteComplete() in progress dialog.

It seems to be issue with Sesssion.cs file .

Here is error I am getting

   at WixToolset.Dtf.WindowsInstaller.Session.Message(InstallMessage messageType, Record record)
   at WixToolset.Dtf.WindowsInstaller.Session.Log(String msg)
   at WixSharp.MsiSessionAdapter.Log(String msg)
   at WixSharp.UtilityFunction.CheckLogs(ISession session, String logmessage) in C:\Sample_Project\WixSharp_TryOuts\WixSharpManagedUI_Sample\UtilityFunction.cs:line 14
   at WixSharpManagedUI_Sample.Dialogs.ProgressDialog.OnExecuteComplete() in C:\Sample_Project\WixSharp_TryOuts\WixSharpManagedUI_Sample\Dialogs\ProgressDialog.cs:line 202
   
   
-----------------------------------------------
   Here is sample code snipet in ProgressDialog
   
      public override void OnExecuteComplete()
      {
          UtilityFunction.CheckLogs(MsiRuntime.Session, "OnExecuteComplete Message ");
          currentAction.Text = null;
          Shell.GoNext();
     }
		
	//Add new class for utility functions
   
    internal class UtilityFunction
    {

        public static void CheckLogs(ISession session, string logmessage="")
        {
            session.Log("This is log from external file : " + logmessage);
        }
    }
	
	
![image](https://github.com/user-attachments/assets/415bf6bc-2f10-4817-bb3c-282ef6b4b05a)

**Comment by bhagatus** [comment]
Thank you for the information. 
Then I think I need to go for another logging mechanism like log4net to be available throughout the execution of setup.
