### ISSUE TITLE
Setup crash in feature selection dialog

### ISSUE THREAD

**Issue by paiden** [oleg-shilo/wixsharp#191]
On a Windows10 VM when testing our setup I had a setup crash. In windows event log I found the following stack trace. 

It seems the crash happens in the managed UI feature selection dialog provided by WixSharp.

```
Application: MsiExec.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.BeginInvoke(System.Delegate, System.Object[])
   at System.Windows.Forms.Control.BeginInvoke(System.Delegate)
   at WixSharp.UIExtensions+<>c__DisplayClass11_0.<ResetCheckedToDefault>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Unfortunately I do not have more information at the moment, as I will need to analyze further. Also I cannot reproduce it reliably. One time the setup crashes, the next time I can execute the whole install sequence without any issues.

**Comment by oleg-shilo** [comment]
Thank you, the information you provided is enough to start the troubleshooting.

Though ideally I would like to catch the exception under debugger. Is it possible for you to provide a "Hello world" style sample that triggers the problem. It is OK if you cannot though. :)

**Comment by oleg-shilo** [comment]
The problem has been corrected.
The fix will be available in the very next release.
Though you can try the fix from the [source code](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples) if you don't want to wait.
