### ISSUE TITLE
Files not getting copied inside Msi_AfterInstall method

### ISSUE THREAD

**Issue by umeshone** [oleg-shilo/wixsharp#259]
Hi Oleg,

I am trying to copy files from a source location to a network path inside the Msi_AfterInstall method, but it's throwing error. Please find the error details below. Here the MSI is being installed through VSTS. But the copy is successful when I am copying it manually or from other GUI based program. In both the cases same User Account is used. Please help. Thanks in advance.

Code snippet:-
```C#
var destDir = e.Session.Property("COPY_TO_DIR");
var sourceDir = e.Session.Property("INSTALLDIR");
e.Session.Log($"Copy files from Source Dir:-{sourceDir} to Destination Dir:-{destDir}");
Microsoft.VisualBasic.FileIO.FileSystem.CopyDirectory(sourceDir, destDir, true);
```
Error Details:-
```
Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
Copy files from Source Dir:-C:\MyApp\ to Destination Dir:-\\siov20893\id$\MyTeam\MyApp
```
Exception Occurred: The user name or password is incorrect.
```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryName, String destinationDirectoryName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at SetupDesktopApp.Program.Msi_AfterInstall(SetupEventArgs e)
   mscorlib
   WixSharp aborted the session because of the error:
   System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The user name or password is incorrect.

   at SetupDesktopApp.Program.Msi_AfterInstall(SetupEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   at WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)
 CustomAction WixSharp_AfterInstall_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

**Comment by oleg-shilo** [comment]
The easiest way to solve this is to have a breakpoint in your event handler and see what exactly causing the problem. There is a sample on debugging custom actions.

This is the code that I have tested and it works just fine for me:
```C#
project.AfterInstall += msi_AfterInstall;

static void msi_AfterInstall(SetupEventArgs e)
{
    if (!e.IsUninstalling)
        foreach (var file in System.IO.Directory.GetFiles(e.InstallDir, "*"))
            System.IO.File.Copy(file, @"C:\Temp\wix#".PathJoin(file.PathGetFileName()), true);
}
```
