### ISSUE TITLE
Relative Path - First build always failing

### ISSUE THREAD

**Issue by Lechl** [oleg-shilo/wixsharp#322]
Hello Oleg,

i'm using a dynamic path to load all needed files into my msi.

`var files = new Files(build.SolutionPath + "*.*");`

where my build.SolutionPath is `"..\\..\\..\\..\\OtherProject\\bin\\x86\\Debug\\ "`

When i make a code change, doesn't matter which - the first build is always failing. The second try always succeeds.
The error i get:

Unhandled Exception: System.IO.DirectoryNotFoundException: C:\Users\MyUser\Documents\MySolution\WixSharpProject\..\..\..\..\OtherProject\bin\x86\Debug
at WixSharp.Files.GetAllItems(String baseDirectory, Dir parentWixDir)
at WixSharp.Project.ResolveWildCards(Boolean ignoreEmptyDirectories)
.......
C:\Users\MyUser\Documents\MySolution\packages\WixSharp.1.6.2.1\build\WixSharp.targets(6,5): error MSB3073: The command ""C:\Users\MyUser\Documents\MySolution\WixSharpProject\bin\x86\Debug\BootstrapperGenerator.exe" "/MSBUILD:BootstrapperGenerator"" exited with code -532459699.

Using VS Prof 2017, Version 15.5.1. Not sure whats going on here. Do you have an idea?

**Comment by Lechl** [comment]
Sorry, my mistake. There was a problem in my build order.
