### ISSUE TITLE
Assembly not found on WixSharp_AfterInstall_Action

### ISSUE THREAD

**Issue by DarioGi** [oleg-shilo/wixsharp#414]
Hi all,

I'm calling a method which is located in assembly "Test" inside an after install action, but I'm getting an exception stating that assembly is not found. The installer does reference the assembly. Any ideas on how to resolve this?

```
ActionStart: Action 11:13:28: WixSharp_AfterInstall_Action. 
Info: SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI51D1.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
Info: WixSharp aborted the session because of the error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Test.InstallerV2.Program.Msi_AfterInstall(SetupEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   at WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)
```

**Comment by DarioGi** [comment]
I added the assembly and all of the dependent assemblies to DefaultRefAssemblies - that seemed to do it.

**Comment by DarioGi** [comment]
> @DarioGi Im facing the same problem, can you please explain what's the DefaultRefAssemblies? How did you add the assembly? Thanks a lot!

If I recall correctly, any code that is used in any of the ManagedActions (e.g AfterInstall, BeforeInstall) that is outside of the installer's assembly should be referenced explicitly via project's DefaultRefAssemblies:

```
var project = new ManagedProject(...);
project.DefaultRefAssemblies.Add("path/to/assembly/file.dll");
project.AtferInstall += AfterInstall;

private static void AfterInstall(SetupEventArgs e)
{
    // You can make any calls from "path/to/assembly/file.dll"
}
```
