### ISSUE TITLE
Error: Specified file could not be executed.

### ISSUE THREAD

**Issue by ssijbabu** [oleg-shilo/wixsharp#433]
While running the command (cscs Code\Setup.cs) i am getting the below error.

```
C:\Wixsharp>cscs Code\Setup.cs
C# Script execution engine. Version 3.12.2.0.
Copyright (C) 2004-2016 Oleg Shilo.

Error: Specified file could not be executed.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Depl
oyment.WindowsInstaller, Version=3.0.0.0, Culture=neutral, PublicKeyToken=ce35f7
6fcda82bad' or one of its dependencies. The system cannot find the file specifie
d.
File name: 'Microsoft.Deployment.WindowsInstaller, Version=3.0.0.0, Culture=neut
ral, PublicKeyToken=ce35f76fcda82bad'
   at WixSharp.Compiler.GenerateWixProj(Project project)
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
   at WixSharp.Compiler.Build(Project project, String path, OutputType type)
   at WixSharp.Compiler.Build(Project project, OutputType type)
   at Script.Main()

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Deployment.WindowsInstaller, Version=3.0.0.0, Cultu
re=neutral, PublicKeyToken=ce35f76fcda82bad
 (Fully-specified)
LOG: Appbase = file:///C:/Wixsharp/
LOG: Initial PrivatePath = NULL
Calling assembly : WixSharp, Version=1.7.0.0, Culture=neutral, PublicKeyToken=37
75edd25acc43c2.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\
v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Deployment.WindowsInstaller, Version=3.0.0
.0, Culture=neutral, PublicKeyToken=ce35f76fcda82bad
LOG: Attempting download of new URL file:///C:/Wixsharp/Microsoft.Deployment.Win
dowsInstaller.DLL.
LOG: Attempting download of new URL file:///C:/Wixsharp/Microsoft.Deployment.Win
dowsInstaller/Microsoft.Deployment.WindowsInstaller.DLL.
LOG: Attempting download of new URL file:///C:/Wixsharp/Microsoft.Deployment.Win
dowsInstaller.EXE.
LOG: Attempting download of new URL file:///C:/Wixsharp/Microsoft.Deployment.Win
dowsInstaller/Microsoft.Deployment.WindowsInstaller.EXE.
```

**Comment by oleg-shilo** [comment]
Ensure that your build script has the correct path to the `...WindowsInstaller.dll`.

This is how one of the samples does it (https://github.com/oleg-shilo/wixsharp/blob/master/Source/src/WixSharp.Samples/Wix%23%20Samples/DTF%20(ManagedCA)/setup.cs):
```C#
//css_dir ..\..\;
//css_ref System.Core.dll;
//css_ref Wix_bin\SDK\Microsoft.Deployment.WindowsInstaller.dll;
using System;
using System.Linq;
using System.Xml.Linq;
...
```

**Comment by ssijbabu** [comment]
Hi Oleg,
Thank you for the response. It works now.
Regards
Sujay
