### ISSUE TITLE
FileLoadException on ManagedProject BeforeInstall

### ISSUE THREAD

**Issue by LGFN** [oleg-shilo/wixsharp#619]
I'm running into an issue where installation runs successfully until I add the `BeforeInstall` event handler to it, at which point installation fails.

Relevant installation log file lines:
```
ActionStart: Action 16:40:14: WixSharp_BeforeInstall_Action. 
Info: Action start 16:40:14: WixSharp_BeforeInstall_Action.
Info: SFXCA: Extracting custom action to temporary directory: C:\Users\xx\AppData\Local\Temp\MSI520B.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_BeforeInstall_Action
Info: WixSharp aborted the session because of the error:
System.IO.FileLoadException: Could not load file or assembly 'WixSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'WixSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at WixSharp.ManagedProject.GetHandler(String info)
   at WixSharp.ManagedProject.InvokeClientHandler(String info, SetupEventArgs eventArgs)
   at WixSharp.ManagedProject.InvokeClientHandlers(Session session, String eventName, IShellView UIShell)

=== Pre-bind state information ===
LOG: DisplayName = WixSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/xx/AppData/Local/Temp/MSI520B.tmp-
LOG: Initial PrivatePath = NULL
Calling assembly : WixSharp, Version=1.9.5.0, Culture=neutral, PublicKeyToken=3775edd25acc43c2.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: <hidden content>
LOG: Using host configuration file: 
LOG: Using machine configuration file from <hidden content>
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/xx/AppData/Local/Temp/MSI520B.tmp-/WixSharp.DLL.
WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Info: CustomAction WixSharp_BeforeInstall_Action returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Info: Action ended 16:40:14: WixSharp_BeforeInstall_Action. Return value 3.
CommonData: Message type: 2, Argument: 0
CommonData: Message type: 2, Argument: 1
Info: Action ended 16:40:14: INSTALL. Return value 3.
InstallEnd: 1: ProgramName 2: {683ABD6F-D01E-40BE-9217-B357D40F5A89} 3: 3 
CommonData: 1: 2 2: 0 
CommonData: 1: 2 2: 1 
Info: Action ended 16:40:14: INSTALL. Return value 3.
```

**Comment by oleg-shilo** [comment]
The most common cause of this sort of problems is the CLR failure to locate the dependency resource (e.g. referenced) assembly. Unfortunatelly CLR never reports the exact cause and it needs to be discovered manually.

I suggest that you try with a simple setup from the samples. If it works then start adding your stuff into it until the problem is triggered.  

You can also provide some test code and I can have a look at it.
