### ISSUE TITLE
ComponentCondition on CloseApplication doesn't appear to be working

### ISSUE THREAD

**Issue by GilesBathgate** [oleg-shilo/wixsharp#696]
I have the following code, which sets a ComponentCondition on the CloseApplication action. 
```c#
 class Program
    {
        static void Main()
        {
            var chromeFeature = new Feature(new Id("ChromeFeature"), true, true);
            var project = new ManagedProject("MyProduct",
                             new Dir(@"%ProgramFiles%\My Company\My Product",
                                 new File(chromeFeature, "Program.cs")),
                              new CustomActionRef("WixCloseApplications", When.Before, Step.CostFinalize, new Condition("VersionNT > 400")),
                              new CloseApplication("chrome.exe", true, false) { ComponentCondition = new Condition("&ChromeFeature=3") });

            project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889b");

            project.BuildMsi();
```

The build fails with the following output:

```
1>------ Build started: Project: Setup1, Configuration: Debug Any CPU ------
1>  Setup1 -> C:\Users\Giles\source\repos\WixSharpSolution\Setup1\bin\Debug\WixSharpSetup.exe
1>  Building MSI
1>  Searching for custom action entry points in WixSharp.dll
1>      Loaded dependent assembly: C:\Program Files (x86)\WiX Toolset v3.11\sdk\Microsoft.Deployment.WindowsInstaller.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
1>      Loaded dependent assembly: C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll
1>      WixSharp_SetPackageName_Action=WixSharp!WixSharp.ResilientPackage.WixSharp_SetPackageName_Action
1>      WixSharp_RemoveResilientPackage_Action=WixSharp!WixSharp.ResilientPackage.WixSharp_RemoveResilientPackage_Action
1>      WixSharp_CreateResilientPackage_Action=WixSharp!WixSharp.ResilientPackage.WixSharp_CreateResilientPackage_Action
1>      WixSharp_InitRuntime_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_InitRuntime_Action
1>      WixSharp_Load_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_Load_Action
1>      WixSharp_BeforeInstall_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_BeforeInstall_Action
1>      WixSharp_AfterInstall_Action=WixSharp!WixSharp.ManagedProjectActions.WixSharp_AfterInstall_Action
1>      CancelRequestHandler=WixSharp!WixSharp.ManagedProjectActions.CancelRequestHandler
1>  Searching for an embedded UI class in WixSharp.dll
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\Users\Giles\source\repos\WixSharpSolution\Setup1\bin\Debug\WixSharp.dll to C:\Users\Giles\source\repos\WixSharpSolution\Setup1\WixSharp.CA.dll
1>  Packaging files
1>      WixSharp.dll
1>      CustomAction.config
1>      Microsoft.Deployment.WindowsInstaller.dll
1>  MakeSfxCA finished: C:\Users\Giles\source\repos\WixSharpSolution\Setup1\WixSharp.CA.dll
1>  
1>  Unhandled Exception: System.ApplicationException: Cannot resolve custom attribute definition:Component:Condition=&ChromeFeature
1>     at WixSharp.AutoElements.ExpandCustomAttributes(XDocument doc, WixProject project)
1>     at WixSharp.AutoElements.InjectAutoElementsHandler(XDocument doc, Project project)
1>     at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.BuildWxs(Project project, OutputType type)
1>     at WixSharp.Compiler.Build(Project project, String path, OutputType type)
1>     at WixSharp.Compiler.Build(Project project, OutputType type)
1>     at Setup1.Program.Main() in C:\Users\Giles\source\repos\WixSharpSolution\Setup1\Program.cs:line 25
1>C:\Users\Giles\source\repos\WixSharpSolution\packages\WixSharp.1.9.5.1\build\WixSharp.targets(5,5): error MSB3073: The command ""C:\Users\Giles\source\repos\WixSharpSolution\Setup1\bin\Debug\WixSharpSetup.exe" "/MSBUILD:Setup1" "/WIXBIN:"" exited with code -532462766.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

It doesn't seem to work with any condition including the build-in ones such as `Condition.Silent`

**Comment by oleg-shilo** [comment]
Will have a look. Txs for reporting.

In a mean time you can go C# way intsead of WiX:
```C#
project.BeforeInstall += project_BeforeInstall;
. . .
static void project_BeforeInstall(SetupEventArgs e) 
{
    if (e.Session.IsUninstalling() && e.Session.IsFeatureEnabled("ChromeFeature"))
        Process.GetProcessesByName("Chrome").ForEach(p => p.Kill());
}
```

To be hones I even prefer C# way :)

**Comment by GilesBathgate** [comment]
That's ok, but I wanted to use this in conjunction with the custom dialog which gives the opportunity for the user to approve the action.

Is there anyway I can add the condition to the Element as CData manually, in much the way I can add custom attributes?

Something like:
```c#
new CloseApplication("chrome.exe", true, false) { ElementBody = "<CDATA[[&ChromeFeature=3]]>") 
```

**Comment by oleg-shilo** [comment]
You can always inject WiX elements/attributes directly to the XML:
```C#
 project.WixSourceGenerated += document =>
        {
            document.Select("Product")
                    .AddElement("MediaTemplate", "CabinetTemplate=cab{0}.cab;" + 
                                                 "CompressionLevel=mszip");

            document.Select("Product/Package")
                    .SetAttributeValue("Platform", "x64");

            document.FindAll("Component")
                    .ForEach(e => e.SetAttributeValue("Win64", "yes"));

            // merge 'Wix/Product' elements of document 
            // with 'Wix/Product' elements of CommonProperies.wxs
            document.InjectWxs("CommonProperies.wxs");
        };
```

**Comment by GilesBathgate** [comment]
Yep, that will be the workaround thanks.

**Comment by oleg-shilo** [comment]
Have a look at WixSharp XML extension methods (e.g. XContainer.Select(string path)) you may find them more convenient than raw XDocument API

**Comment by GilesBathgate** [comment]
This was the workaround I used:

```c#
project.WixSourceGenerated += FixCloseActionConditions;

private static void FixCloseActionConditions(XDocument document)
{
            var ns = XNamespace.Get("http://schemas.microsoft.com/wix/UtilExtension");
            var closeApplication = document.Descendants(ns + "CloseApplication");
            foreach(var element in closeApplication)
            {
                if (element.Attribute("Target")?.Value == "chrome.exe")
                    element.Value = "&ChromePlugin=3";
            }
}
```

Still would be good to have a fix though.

**Comment by oleg-shilo** [comment]
OK, I finally found time to look at this issue. A few points...

1. If you use WixSharp LINQ XML extensions your very work around can become much simpler:
    ```C#
    project.WixSourceGenerated +=
            doc => doc.FindAll("CloseApplication")
                      .Where(x => x.HasAttribute("Target", "chrome.exe"))
                      .ForEach(x => x.Value = "&ChromePlugin=3");

    ```
2. About the error. Strictly speaking it's not a defect as you were trying to set an attribute to the parent `Component` element. However `CloseAplication` is never contained by a `Component` but only by `Product`. Meaning that the operation you were trying to perform were guaranteed to fail.

    In order to address the ambiguity of the error message I have reworked the excxeption. Now it throws like that:
    ```
    Unhandled Exception: System.ApplicationException: Cannot resolve custom attribute definition:Component:Condition=&ChromeFeature
    Note, some Wix elements may not be contained by 'Component' elements (e.g. 'CloseApplication'). Thus attempt to set parent component attribute will always fail.

     at WixSharp.AutoElements.ExpandCustomAttributes(XDocument . . .
    ```
    I have also updated the XML doc for `ComponentCondition`:

    ![image](https://user-images.githubusercontent.com/16729806/63211893-ca714780-c140-11e9-9c80-370628c0685d.png)

3. To address your feature request a new `Condition` member has been added to the `CloseApplication` class:
    ```C#
    new CloseApplication(new Id("notepad"), "notepad.exe", true, false)
    {
        Timeout = 15,
        Condition = new Condition("&ChromeFeature=3")
    }
    ```

I will release the fix as a HotFix release today/tomorrow
