### ISSUE TITLE
NullReferenceException on FindClientAssemblyInCallStack

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#786]
When upgraded from 1.13.2 to 1.14.0, I am receiving a NullReferenceException:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WixSharp.Compiler.FindClientAssemblyInCallStack()
   at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
   at (Object , OutputType , String )
   at SIDY.JF.W(Object , OutputType , String )
   at Invantive.Deploy.ProjectBase.Build()
   at Invantive.SupportAssistant.Setup.Program.Main()
```

**Comment by monty241** [comment]
Was able to reproduce by calling this code from my own code:
```
        internal static string FindClientAssemblyInCallStack()
        {
            var st = new StackTrace(false);
            for (int i = 0; i < st.FrameCount; i++)
            {
                if (st.GetFrame(i) == null) { throw new Exception("3"); }
                if (st.GetFrame(i).GetMethod() == null) { throw new Exception("3b"); }
                if (st.GetFrame(i).GetMethod().DeclaringType == null) { throw new Exception("3c"); }
                var asm = st.GetFrame(i).GetMethod().DeclaringType.Assembly;
                if (asm != System.Reflection.Assembly.GetExecutingAssembly())
                {
                    if (asm == "".GetType().Assembly || asm.FullName.StartsWith("mscorlib."))
                        // being executed as a release-compiled script
                        return Environment.GetEnvironmentVariable("EntryScriptAssembly");
                    else
                        return asm.GetLocation();
                }
            }
            return null;
        }
```

This one throws 3c, so the declaring type is null. Maybe good to rewrite add "?" and "if":

```
                var asm = st.GetFrame(i).GetMethod().DeclaringType?.Assembly;
                if (asm != null && asm != System.Reflection.Assembly.GetExecutingAssembly())

```

**Comment by oleg-shilo** [comment]
Yep, I expected that when the change is on the field some edge cases could be discovered.

I will update the implementation to handle your use-case and as temp workaround you can use assign client assembly explicitly from the build script implementing your managed project or CA:

```C#
Compiler.ClientAssembly = System.Reflection.Assembly.GetExecutingAssembly().GetLocation();
. . .
project.BuildMsi();
```

**Comment by monty241** [comment]
Thanks for the helpful workaround. Applied it and works fine: no NRE thrown anymore and software still installs :-).

**Comment by oleg-shilo** [comment]
Great. The whole business case for `FindClientAssemblyInCallStack` was to avoid forcing the user to assign `Compiler.ClientAssembly` manually. But if `FindClientAssemblyInCallStack` fails then manual assigning is the way to go.
